/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   mixins/declarative-event-listeners.html
 */

declare namespace Polymer {


  /**
   * Element class mixin that provides API for adding declarative event
   * listeners nodes.
   *
   * The API is designed to be compatible with override points implemented
   * in `Polymer.TemplateStamp` such that declarative event listeners in
   * templates will support gesture events when this mixin is applied along with
   * `Polymer.TemplateStamp`.
   */
  function DeclarativeEventListeners<T extends new (...args: any[]) => {}>(base: T): T & DeclarativeEventListenersConstructor;

  interface DeclarativeEventListenersConstructor {
    new(...args: any[]): DeclarativeEventListeners;
  }

  interface DeclarativeEventListeners {
    ready(): any;
  }
}
